import Providers from "@/redux/providers"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"
import "swiper/css"
import "swiper/css/effect-fade"
import "swiper/css/navigation"
import "swiper/css/pagination"

import Footer from "./(sections)/footer"
import Header from "./(sections)/header"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<Providers>
			<html lang="en">
				<body className={`${inter.className} overflow-x-hidden`}>
					<Header />
					<ToastContainer hideProgressBar stacked position="top-center" />
					<section className="bg-black overflow-x-hidden">
						{children}
						<Footer />
					</section>
				</body>
			</html>
		</Providers>
	)
}
