import Providers from "@/redux/providers"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "swiper/css"
import "swiper/css/effect-fade"
import "swiper/css/navigation"
import "swiper/css/pagination"

import Footer from "./(sections)/footer"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<Providers>
			<html lang="en">
				<body className={inter.className}>
					<section className="bg-black overflow-x-hidden">
						{children}
						<Footer />
					</section>
				</body>
			</html>
		</Providers>
	)
}
