name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Check node version
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.x"
      # Install packages
      - name: Install dependencies
        run: npm ci
        # Check eslint
      - name: Check eslint
        run: npm run lint
      - run: npm run build --if-present
    #   - run: npm test
